### ISSUE TITLE
current todo list

### ISSUE THREAD

**Issue by Catz-uwu** [RasmusAntons/helper#1]
- [x] finalize "inactive" svgs
- [x] add edited.svg to corner of blocks
- [x] create new favicon
- [x] change tab name
- [x] reorder buttons at the top
- [x] create draft of the category section
- [x] find compact color picking widget 
- [x] add style to category section
- [x] integrate new edited marker
- [x] add inactive markers
