### ISSUE TITLE
second todo list

### ISSUE THREAD

**Issue by Catz-uwu** [RasmusAntons/helper#2]
- [ ] add functionality to categories menu
- [ ] add category selection to levels toolbar
- [ ] link categories to level blocks
- [ ] create configurations menu
- [ ] hide configuration menu unless its button is clicked on
- [ ] start coming up with line styles and colors
