### ISSUE TITLE
third todo list omg??

### ISSUE THREAD

**Issue by Catz-uwu** [RasmusAntons/helper#4]
- [x] move save button to the bottom and add a margin above it
- [x] font loading issue fix
- [x] make role / channel / extra role deletion work from dialog
- [x] add guild id to configurations
- [x] modify rainbow animation to include teal and blue instead of olive
- [x] add class for currently selected category
- [x] split the javascript into multiple files for readability
- [x] load key and bot token to configurations menu and allow edits
- [x] add edited marker to categories and configurations buttons
- [x] create dialog for setting role / channel / category names
- [x] add edited marker to save button if at least one change as occurred anywhere
- [x] create dialog for closing window with unsaved changes
- [x] lines
- [x] make it so that create line and create button block look active until done
- [x] create new level with csgo mode
